services:
  mailserver:
    image: 'ghcr.io/docker-mailserver/docker-mailserver:latest'
    hostname: mail
    domainname: monynha.com
    environment:
      OVERRIDE_HOSTNAME: mail.monynha.com
      POSTMASTER_ADDRESS: postmaster@monynha.com
      TZ: Europe/Lisbon
      ENABLE_IMAP: '1'
      ENABLE_POP3: '0'
      ENABLE_OPENDKIM: '1'
      ENABLE_OPENDMARC: '1'
      ENABLE_POLICYD_SPF: '1'
      PERMIT_DOCKER: none
      POSTFIX_INET_PROTOCOLS: ipv4
      DOVECOT_INET_PROTOCOLS: ipv4
      SSL_TYPE: manual
      SSL_CERT_PATH: /certs/fullchain1.pem
      SSL_KEY_PATH: /certs/privkey1.pem
      TLS_LEVEL: modern
      RELAY_HOST: smtp.resend.com
      DEFAULT_RELAY_HOST: '[smtp.resend.com]:587'
      RELAY_PORT: '587'
      RELAY_USER: resend
      RELAY_PASSWORD: SMTP_PASSWORD
      ENABLE_RELAYHOST: '1'
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '143:143'
      - '993:993'
    volumes:
      - 'mail-data:/var/mail'
      - 'mail-state:/var/mail-state'
      - 'mail-logs:/var/log/mail'
      - 'mail-config:/tmp/docker-mailserver'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/letsencrypt/archive/mail.monynha.com:/certs:ro'
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - mailnet
    healthcheck:
      test:
        - CMD-SHELL
        - "ss --listening --ipv4 --tcp | grep -q ':smtp'"
      timeout: 3s
      retries: 3
  roundcube:
    image: 'roundcube/roundcubemail:latest'
    depends_on:
      - mailserver
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: 'ssl://mail.monynha.com'
      ROUNDCUBEMAIL_DEFAULT_PORT: '993'
      ROUNDCUBEMAIL_SMTP_SERVER: 'tls://mail.monynha.com'
      ROUNDCUBEMAIL_SMTP_PORT: '587'
    volumes:
      - 'roundcube-data:/var/roundcube'
      - 'roundcube-db:/var/roundcube/db'
    expose:
      - '80'
    restart: unless-stopped
    networks:
      - mailnet
networks:
  mailnet: null
volumes:
  mail-data: null
  mail-state: null
  mail-logs: null
  mail-config: null
  roundcube-data: null
  roundcube-db: null
